### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1402]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/go/issues/1393)
- [x] [Add key features](https://github.com/exercism/go/issues/1394)
- [x] [Add tags](https://github.com/exercism/go/issues/1395)
- [x] [Update status of track](https://github.com/exercism/go/issues/1400)
- [x] [Update status of Concept Exercises](https://github.com/exercism/go/issues/1401)
- [x] [Pass linting checks](https://github.com/exercism/go/issues/1397)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/go/issues/1396)
- [ ] [Build Test Runner](https://github.com/exercism/go/issues/1398)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/go/issues/1399) (optional)
- [ ] [Add blurb to Concept Exercises](https://github.com/exercism/go/issues/1427)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by jmrunkle** [comment]
@ErikSchierboom - I take it this issue can be closed. Please re-open if I was mistaken.
