### ISSUE TITLE
Separate concepts `conditionals-if` and `comparison` into their own new exercise

### ISSUE THREAD

**Issue by junedev** [exercism/go#1934]
## Getting started
Here you can read about what Concept Exercises are and how they are structured:

- [What are Concept Exercises?](https://exercism.org/docs/building/product/concept-exercises)
- [Concept Exercises](https://exercism.org/docs/building/tracks/concept-exercises)
- [Concepts](https://exercism.org/docs/building/tracks/concepts)

If you have not done so yet, it is probably also helpful to do a couple of "Learning Exercises" (this is how they are called on the site) yourself. You can also look at the code of an existing concept exercise like [`welcome-to-tech-palace`](https://github.com/exercism/go/tree/main/exercises/concept/welcome-to-tech-palace) for reference.

## Motivation
Currently, the concept exercise `cars-assemble` teaches 4 concepts. We want to split that exercise into one exercise that teaches `numbers` and `arithmetic-operators` (`cars-assemble`) and one exercise that teaches `conditionals-if` and `comparison` (`vehicle-purchase`).

Why?
* This would help getting the concept tree in better shape. It makes more sense to have the basic types as the first "layer" below `basics` and then once that layer is completed you move on to the conditionals etc.
* 4 concepts for one exercise is really a lot even if they are not that difficult.
* Currently the exercise does not practice much of each concept, that could be improved with the split.

## Task
Create a new exercise `vehicle-purchase` that teaches 2 concepts, `conditionals-if` and `comparison`. The exercise can be ported from JavaScript: https://github.com/exercism/javascript/tree/main/exercises/concept/vehicle-purchase. The two concepts already exist in the concepts folder, you don't need to write those.

This involves the following.

- [ ] set up the basic exercise files and folders
- [ ] add the new exercise with status "beta" to the root level `config.json` (prerequisite concepts should be set to `strings`, `numbers` and `booleans`)
- [ ] port the `.docs/instructions.md` file from JavaScript
- [ ] fill the `.docs/introduction.md` file by copying the relevant parts from the `cars-assemble` exercise introduction file
- [ ] fill `.meta/config.json`
- [ ] port/write the `.meta/exemplar.go` file
- [ ] port/write the `.docs/hints.md` file
- [ ] set up the stub file `vehicle_purchase.go`
- [ ] port/write the tests `vehicle_purchase_test.go`
- [ ] write the `.meta/design.md` file

## Out of Scope

Removing `conditionals-if` and `comparison` is out of scope for this issue. There will be another issue dealing with this.

## How to proceed

1. Accept this issue by saying "I'd like to work on this" (no need to wait for a response, just go with it).
2. Use this issue to discuss any questions you have.
3. Create a PR and set "exercism/go" as reviewers when you are done. Additionally you can write in #maintaining-go that your PR is ready for review. Once you incorporated any critical feedback that the reviewer might give you and the PR is approved, it will be merged by a maintainer.

**Comment by kahgoh** [comment]
I'd like to work on this

**Comment by andrerfcsantos** [comment]
@kahgoh Glad to hear! I assigned this task to you. Don't hesitate to ask any questions you may have while doing this.

**Comment by kahgoh** [comment]
I have been looking at porting the tests from the Javascript version. I was wondering how closely does the exercise has to follow the Javascript version?

The reason I was asking is because I noticed in the Javascript version, the `ChooseVehicle` tests were expecting students to write a function that:
1. choose one of the vehicles from one of the parameters
2. return the chosen vehicle as part of a sentence (e.g. `Toyota Corolla is clearly the better choice.`)

I was thinking of changing its test to expect just the vehicle name instead. For example, just `Toyota Corolla`. I think it will help reduce the focus on `strings` and more on the `conditions` and `conditional-if` concepts, although it would deviate more from the Javascript version.

**Comment by junedev** [comment]
@kahgoh The additional part in the result in that task exists to discourage early returns (with that additional part they would lead to duplication). For chooseVehicle, I agree it doesn't make that much of a difference when a student sets one of the options as default at the beginning of the function. I still like that is is a little more involved than "return option2" and practices string concatenation but you can change the exercise if you feel differently. For the last task however, I would recommend sticking with the JavaScript version that includes this small calculation.

In general feel free to change the exercise as you like. You can also create a new one from scratch if you have an idea in mind. Porting an existing exercise is just a proposal to make things easier/faster but no "must".
