### ISSUE TITLE
Card Tricks: Adapt to current concept tree progression

### ISSUE THREAD

**Issue by junedev** [exercism/go#1990]
## Getting Started

If you have not yet contributed to concept exercises before, this task requires some upfront reading to acquire the necessary background knowledge.

Here you can read about what Concept Exercises are and how they are structured:

- [What are Concept Exercises?](https://exercism.org/docs/building/product/concept-exercises)
- [Concept Exercises](https://exercism.org/docs/building/tracks/concept-exercises)
- [Concepts](https://exercism.org/docs/building/tracks/concepts)

## Motivation

Currently the concept exercise "Card Tricks" has some issues.
1. It requires the student to know about `for-loops` which are taught later in the [syllabus](https://exercism.org/tracks/go/concepts) and depend on `slices`.
2. It requires the student to know about variadic functions (`append` in this case) which were not introduced yet.
3. `multiple-return-values` is now part of the `functions` concept and should not be taught as part of Card Tricks anymore.

These issues should be addressed.

## Tasks

- [ ] Remove the task about `PrefilledSlice` from all the relevant exercise files (it requires for loops).
- [ ] Optional (can also be done later as a separate issue/PR): As replacement for `PrefilledSlice` it would be good to have another task that requires the student to create a slice. Additionally, the student should get a task that requires to define a variadic function.
- [ ] Change `GetItem` to have only one return value. In case the index is out of range, `-1` should be returned. Make sure to apply the change consistently (check hints, instructions etc.).
- [ ] Add the content of `concepts/variadic-functions/introductions.md` to the introductions file of the exercise. A good structure would be
  - `# Introduction`
  - `## Slices` (the content in slices should mention that append is a variadic function and refer to the details below)
  - `## Variadic Functions`
- [ ] Update the root level config.json file:
  - Remove `multiple-return-values` from the concepts taught by `card-tricks`.
  - Add `variadic-functions` to the concepts taught by `card-tricks`.
  - There are 2 other exercises that have `multiple-return-values` as prerequisite. Change the concept name to `functions` for those.
  
## Out of Scope

- Writing the `variadic-functions` concept is a separate issue.
- Entirely removing the `multiple-return-values` concept will be separate issue.

---

If you want to work on this issue, just leave a comment below and go ahead. No need to wait for a reply.

**Comment by junedev** [comment]
I noticed another thing regarding this exercise. It would be good if `SetItem` would have a test case that checks that the student did not copy the slice.

**Comment by shakhzodkudratov** [comment]
@junedev maybe it will be better to include more articles in the syllabus concepts. The student should understand them and not need to check them in tests.

**Comment by junedev** [comment]
@shakhzodkudratov As I explained in our mentoring session, the conceptual understanding how the slice is passed to the function here should come from the functions concept (exercise "Lasagna Master"). I will make a separate issue regarding improvements there.

Additionally, when we add that test case I mentioned, we can use the hints to help out students where that new test case might fail.

**Comment by norbs57** [comment]
I am happy to work on this.
